### ISSUE TITLE
Rebound Fee higher than 1.0

### ISSUE THREAD

**Issue by Exxibition** [chainx-org/chainx-dapp-wallet-bug#2]
Hi, short question. Is it correct that the fee for rebounding a vote to a different validator wen't up from 0.08 PCX to 1 PCX? Is there a reason for this increase or is that something that will be changed back to 0.08?

**Comment by liuchengxu** [comment]
It's always discouraged to rebond frequently and ChainX 2.0 is much stable than 1.0. Anyway, the fee can be adjusted by the governance though.
